### ISSUE TITLE
ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/bullmq#901] opened 2021-11-30 05:29 UTC
## Error

```
2021-11-30 05:05:13.668  ERROR
Error  ENOENT: no such file or directory, scandir '/home/server/node_modules/<my-app>/commands'
details:
{
	errno: -2,
	code: 'ENOENT',
	syscall: 'scandir',
	path: '/home/server/node_modules/<my-app>/commands'
}
```

## Context

Bundling with `esbuild` causes the error above to crash the application.

Possible causes:
- **https://github.com/taskforcesh/bullmq/blob/437d9b35251fca132f56f1e075b84f5cdccebbde/src/classes/redis-connection.ts#L122**
- **https://github.com/taskforcesh/bullmq/blob/437d9b35251fca132f56f1e075b84f5cdccebbde/src/classes/redis-connection.ts#L126**
- https://github.com/taskforcesh/bullmq/blob/9d108e30fbd47de3f4b32d2217bce8a1d0c9400c/yarn.lock#L328
- https://github.com/taskforcesh/bullmq/blob/7619e232faf759c0456e83bef7b35064278f2453/src/commands/index.ts#L21
- https://github.com/taskforcesh/bullmq/blob/7619e232faf759c0456e83bef7b35064278f2453/src/commands/index.ts#L77

## Suggested Solution

Not entirely sure what the purpose of loading these files directly from the file system is, but if the goal is to simply arrive at having the content of the `.lua` files available in javascript, then I would highly recommend provided them as string templates.

Most bundlers will have a lot of issues dealing with direct access to files like this as they flatten a lot of things during build, so importing the files as `javascript` is the only way for them to be preserved properly.

### Example

```typescript

// ../commands/drain-4.lua.ts

export default `
--[[
  Drains the queue, removes all jobs that are waiting
  or delayed, but not active, completed or failed
  Input:
    KEYS[1] 'wait',
    KEYS[2] 'paused'
    KEYS[3] 'delayed'
    KEYS[4] 'priority'
    ARGV[1]  queue key prefix
]]
local rcall = redis.call
local queueBaseKey = ARGV[1]

local function removeJobs (list)
  for _, id in ipairs(list) do
    rcall("DEL", queueBaseKey .. id)
  end
end

local wait_ids = rcall("LRANGE", KEYS[1] , 0, -1)
local paused_ids = rcall("LRANGE", KEYS[2] , 0, -1)

removeJobs(wait_ids)
removeJobs(paused_ids)

if KEYS[3] ~= "" then
  local delayed_ids = rcall("ZRANGE", KEYS[3] , 0, -1)
  removeJobs(delayed_ids)
  rcall("DEL", KEYS[3])
end

rcall("DEL", KEYS[1])
rcall("DEL", KEYS[2])
rcall("DEL", KEYS[4])
`
```

## Environment

- Alpine Linux
- Node 16
- BullMQ ^1.54.5

**Comment by manast** [comment] 2021-11-30 10:36
AFAIK it is working well with webpack. There is probably some tweak that can be done in esbuild as well so that it works.

**Comment by mikecann** [comment] 2021-12-06 03:38
I too am having issue with esbuild with this library :(

**Comment by Niek** [comment] 2021-12-06 11:36
The problem is that `readFile()` and similar will mess up bundlers (I think WebPack will have the same problem). See for reference: https://github.com/evanw/esbuild/issues/1534

If the BullMQ code is changed to the `import lua from './file.lua'`, this will fix the bundling issues. As a bonus, it's much more TS-alike and conciser too.

**Comment by aledalgrande** [comment] 2022-04-18 00:50
@manast it has already been reported in https://github.com/taskforcesh/bullmq/issues/901 that Webpack breaks when bundling bullmq

**Comment by aledalgrande** [comment] 2022-04-18 01:08
fwiw adding `bullmq` to the externals and then copying `dist/cjs/commands` under your `dist/node_modules` folder is a workaround

**Comment by dwayneyuen** [comment] 2022-05-21 18:58
I'm experiencing this as well, not sure if its exactly the same but I see the same error message during local development if I have a project which depends on bullmq and I have a second project which depends on the first project.

If I publish the first project on NPM things works fine, but if I locally use `npm install ../path-to-package` or `npm link` then I see the same error:

```bash
[Error: ENOENT: no such file or directory, scandir '/Users/dwayneyuen/Devel/my-package/.next/server/pages/api/commands'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/dwayneyuen/Devel/my-package/.next/server/pages/api/commands'
}
```

I don't have a great solution other than finding the offending file and replacing `__dirname` with the physical path that the source file resides in.

For `bullmq` version `1.83.0` for me this is in `my-package/node_modules/bullmq/dist/cjs/classes/redis-connection.js` in the `loadCommands()` function.

So instead of :
```js
loadCommands() {
   return (this._client['bullmq:loadingCommands'] ||
     (this._client['bullmq:loadingCommands'] = commands_1.scriptLoader.load(this._client, path.join(__dirname, '../commands'))));
```

I manually write this:

```js
loadCommands() {
  return (this._client['bullmq:loadingCommands'] ||
    (this._client['bullmq:loadingCommands'] = commands_1.scriptLoader.load(this._client, path.join("/Users/dwayneyuen/my-package/node_modules/bullmq/dist/cjs/classes", '../commands'))));
}
```

**Comment by MarceloPrado** [comment] 2022-09-18 15:57
You can workaround this error by using the `external` [flag](https://esbuild.github.io/getting-started/#bundling-for-node). Example:
```
esbuild --platform=node --format=cjs ./server.ts --outdir=build --bundle --external:bullmq
```

This will tell esbuild to **not** bundle `bullmq`:
> You also may not want to bundle your dependencies with esbuild. There are many node-specific features that esbuild doesn't support while bundling such as __dirname, import.meta.url, fs.readFileSync, and *.node native binary modules. You can exclude all of your dependencies from the bundle by marking them as [external](https://esbuild.github.io/api/#external). 
> 
> If you do this, your dependencies must still be present on the file system at run-time since they are no longer included in the bundle.

**Comment by prescience-data** [comment] 2022-09-18 20:33
Unfortunately this prohibits the use of Bull in scenarios where a complete bundle is required, for example when packaging as a single binary for use outside of a Node environment.

Time constraints meant I had to abandon Bull in favour of another solution (for the project that required this) but my plan (had I the time) was to develop a build-time filesystem reader to consume all these external files to make them available within the bundler.

**Comment by manast** [comment] 2022-09-19 11:41
@prescience-data interesting. I am bundling both Bull and BullMQ with vercel's pkg (https://github.com/vercel/pkg) and it works just fine...

**Comment by roggervalf** [comment] 2022-10-19 04:13
@prescience-data please try last versión, this should be fixed

**Closed by roggervalf** 2022-10-19 04:13 UTC
Labels: enhancement
