### ISSUE TITLE
stalledInterval not working properly

### ISSUE THREAD

**Issue by Wolvan** [taskforcesh/bullmq#286] opened 2020-10-16 13:56 UTC
**BullMQ Version: 1.9.0**

Trying to change the `stalledInterval` on a `QueueScheduler` does not seem to work properly.

My demo setup is this:

`scheduler.js`
```js
"use strict";
const QueueScheduler = require("bullmq").QueueScheduler;
new QueueScheduler("testQ", {
    stalledInterval: 10000
});
```

`worker.js`
```js
"use strict";
const Worker = require("bullmq").Worker;
new Worker("testQ", async (job) => {
    console.log(`Beginning Stalling: ${job.name} (${job.id})`);
    const a = new Date();
    while (new Date() - a < 40000) {} // Stall for 40 seconds
});
```

`task-adder.js`
```js
"use strict";
const Queue = require("bullmq").Queue;
const queue = new Queue("testQ");
async function addTasks() {
    await queue.add(`testJob`, {
        attempts: 3,
        backoff: {
            type: "fixed",
            delay: 0
        }
    });
    queue.disconnect();
}
addTasks();
```

I start up 1 scheduler, then 1 worker and then I run `task-adder` once to kick the entire test off.

Attempting to set `stalledInterval` to 0 causes the following error message:
```
(node:18963) UnhandledPromiseRejectionWarning: ReplyError: ERR Error running script (call to f_890be59efdd64a4df5f5121df9680b166a884036): @user_script:28: ERR invalid expire time in set
    at parseError (PROJECT/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (PROJECT/node_modules/redis-parser/lib/parser.js:302:14)
(node:18963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
According to what I read in the documentation, `0` should turn the stalling check off, is that correct?

Futhermore, when I set `stalledInterval` to `10000`, it should mark a job as stalled after 10 seconds, right? This does not happen for me and the 30 second default timeout is used instead.

The worker also stops processing when it recovers from the artificial stalling and finishes processing the task, erroring due to a missing lock. There are definitely more jobs on the queue for it to process.

**Comment by manast** [comment] 2020-10-19 11:08
Where in the documentation do you read that 0 disables the stalledIntervall?

**Comment by manast** [comment] 2020-10-19 13:17
Regarding the other problem with worker not processing after stalled jobs, it is a duplicate of this one #215
I just removed to emit error event to solve this, I think it is not so critical to be able to listen to that event anyways.

**Closed** 2020-10-19 14:57 UTC

**Comment by Wolvan** [comment] 2020-10-22 08:11
The doc is unfortunately severely lacking on any kind of information regarding `stalledInterval`. I admit, the setting to 0 to disable has come from the original bull package (see [this part of the reference](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue)).

That also leaves the last part of the post open though. Setting the timeout to `10000` did not cause the stalledInterval on the scheduler to change. It still uses the default 30 second timeout.

**Comment by manast** [comment] 2020-10-22 08:18
@Wolvan have you tried the new version 1.10.0 ?

**Comment by Wolvan** [comment] 2020-10-22 08:26
Yes, I did. The worker keeps processing even with the missing lock error, but the stalledInterval (even though I set it to 10000) still stays at around 30-32 seconds.

**Comment by manast** [comment] 2020-10-22 08:35
I am not able to reproduce that. In any case, why would you like to change the stalledIntervall, this is not something very common to do.

**Comment by Wolvan** [comment] 2020-10-22 08:36
Because I have jobs that have the potential to stall. I guess I should be using a sandbox'd script instead?

**Comment by manast** [comment] 2020-10-22 08:38
yeah, that would be better. CPU intensive jobs that block the nodejs loop for long time are problematic if run in the same process as the token renewer (which runs twice as fast as the stalled intervall).

**Comment by Wolvan** [comment] 2020-10-22 08:45
I see. I'll take that suggestion to heart, then
