### ISSUE TITLE
[Bug]: QueueEvents logs keep multiplying

### ISSUE THREAD

**Issue by notflip** [taskforcesh/bullmq#1996] opened 2023-06-17 11:58 UTC
### Version

v3.15.6

### Platform

NodeJS

### What happened?

I have a Plan Queue and a Print Queue, the plan queue is a repeatable event that fires every 2 hours (every minute while testing). **The plan queue adds jobs to the print queue**, but every time it does so (so every minute while testing, I see node processes duplicating and my console output doubles, triples and keeps multiplying.

### How to reproduce.

index.ts
```typescript
// Plan Queue and Plan Worker
export const planQueue = new Queue('plan', { connection });

const planWorkerFile = path.join(__dirname, 'worker-plan.ts');
new Worker('plan', planWorkerFile, { connection });

const planEvents = new QueueEvents('plan', { connection });
planEvents.on('completed', ({ jobId }) => {
    console.log('2. plan job done with id', jobId);
});
planEvents.on('failed', ({ jobId, failedReason }) => {
    console.error('2. plan job failed with id', jobId, failedReason);
});

// Print Queue and Print Worker
export const printQueue = new Queue('print', { connection });

const printWorkerFile = path.join(__dirname, 'worker-print.ts');
new Worker('print', printWorkerFile, { connection });

const printEvents = new QueueEvents('print', { connection });
printEvents.on('completed', ({ jobId }) => {
    console.log('3. print job done with id', jobId);
});
printEvents.on('failed', ({ jobId, failedReason }) => {
    console.error('3. print job failed with id', jobId, failedReason);
});

// Add the repeatable job
async function run(): Promise<any> {
    await planQueue.add('planned-job', {}, {
        repeat: {
            pattern: '* * * * *'
        }
    })
}

run()
    .then(() => console.log('Cron job added'))
    .catch(e => console.error(e))
```

worker-plan.ts
```typescript
import { Job } from "bullmq";
import { printQueue } from "./index";

export default async function (job: Job) {
    await printQueue.add('print', { test: 1 })
}
```

worker-print.ts
```typescript
import { Job } from "bullmq";

export default async function (job: Job) {
    return job.data
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ramiloif** [comment] 2023-06-19 12:26
Hi
what this method returns? `getCompletedTasks`

**Comment by notflip** [comment] 2023-06-19 13:11
> Hi what this method returns? `getCompletedTasks`

Hi @ramiloif just a list of completed tasks, nothing relevant. The example also happens when the job does nothing.

**Comment by manast** [comment] 2023-06-19 13:29
Can you please simplify the code and remove all external dependencies so that we can reproduce the issue? thanks.

**Comment by notflip** [comment] 2023-06-19 20:05
Thanks @manast , I simplified my example and tested again with the simplified code, it's happening.
**It has to do with my one queue adding a job to another queue, it seems to keep multiplying the whole stack**

**Comment by manast** [comment] 2023-06-19 21:07
You are importing the whole index.ts on the worker-plan worker, so for every new process spawn for that worker you are running a new index which in turn creates new workers and so on ad infinitum.
The solution is to not import the same file that spawns the workers from the worker.

**Comment by notflip** [comment] 2023-06-20 04:19
@manast Thanks, should I just re-create the queue connection for the print queue inside the worker file then? `const printQueue = new Queue('print', { connection });` or how would you reference my other queue inside the worker?

**Comment by ramiloif** [comment] 2023-06-20 07:49
So this is not a bug . can we close it ?

**Comment by manast** [comment] 2023-06-20 08:37
@notflip I am not sure how you are doing, but the code above works as expected since you are running new worker instances and adding global workers continuously. Just changing the code to this should fix it:
```ts
import { Job, Queue } from "bullmq";

// TODO: connection opts taken from envs or something.
const printQueue = new Queue('print', { connection });

export default async function (job: Job) {
    await printQueue.add('print', { test: 1 })
}
```

**Comment by notflip** [comment] 2023-06-20 11:01
Thanks @manast I'll give it a shot.

**Closed** 2023-06-20 16:00 UTC
Labels: bug
