### ISSUE TITLE
[Bug]: Command queue state error

### ISSUE THREAD

**Issue by robhicks** [taskforcesh/bullmq#2505] opened 2024-04-02 23:05 UTC
### Version

v5.5.0

### Platform

NodeJS

### What happened?

Since I couldn't figure out how to get Redis connection events from BullMQ directly, I have attempted to create IORedis connections directly, and then pass those connections to workers and queues. 

I have also added, as described in the [IORedis documentation](https://github.com/redis/ioredis/blob/v4/API.md#redismonitorcallback), a monitor function so I can debug potential errors. 

Here's an example: 

```Javascript
import { Queue } from 'bullmq'
import { redisConnection } from './config.js'
import IORedis from 'ioredis'

const { host, port } = redisConnection.connection

const connection = new IORedis(+port, host, { maxRetriesPerRequest: null })

export const jobs = new Queue('jobs', { connection })

connection.monitor((err, monitor) => {
  console.log(`err`, err)
  // if (monitor) {
  //   monitor.on('monitor', (time, args, source, database) => {
  //     console.log(time, args, source, database)
  //   })
  // }
})

```

The error logger emits this:

```bash
err Error: Command queue state error. If you can reproduce this, please report it. Last reply: 1712098529.327989 [0 127.0.0.1:62763] "info"
    at DataHandler.shiftCommand (/Users/robhicks/dev/rqas-nodejs/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/DataHandler.js:173:27)
    at DataHandler.returnReply (/Users/robhicks/dev/rqas-nodejs/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/DataHandler.js:50:27)
    at JavascriptRedisParser.returnReply (/Users/robhicks/dev/rqas-nodejs/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/Users/robhicks/dev/rqas-nodejs/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/Users/robhicks/dev/rqas-nodejs/node_modules/.pnpm/ioredis@5.3.2/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
node:events:495
      throw er; // Unhandled 'error' event
```

### How to reproduce.

See the code snippet above. 

The version of IORedis is 5.3.2.
The version o f NodeJS is 18.19.1
The Redis server version is 7.2.4

### Relevant log output

```shell
See above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment] 2024-11-24 20:10
@fgozdz please try to reproduce this issue and if not possible close it, this seems completely standard initialisation code and should work. Most likely something is missing in the description to be able to reproduce it.

**Comment by fgozdz** [comment] 2024-11-28 14:46
Unfortunately, I am unable to reproduce it, so I will close the issue.

**Closed by fgozdz** 2024-11-28 14:46 UTC
Labels: bug
