### ISSUE TITLE
[Bug]: FlowProducer triggers MaxListenersExceededWarning

### ISSUE THREAD

**Issue by nordicgit70** [taskforcesh/bullmq#2166] opened 2023-09-03 06:02 UTC
### Version

v4.8.0

### Platform

NodeJS

### What happened?

The FlowProducer triggers MaxListenersExceededWarning. 

This happens when a new FlowProducer is created each time a new flow (job) is created. The FlowProducer constructor is called with the queue options of the queue that will be the parent for the flow, and without connection parameter.

```
this.#producer = new FlowProducer({ ...queue.opts });
```

The stack trace in the log contains `new RedisConnection` but the warning indicates that it add listeners to an existing connection and that these listeners are not clean-up.

### How to reproduce.

Multiple calls to an API endpoint that creates a flow according the above code.

### Relevant log output

```shell
Sep 02 16:38:28 X app/web.1 (node:43) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit 
Sep 02 16:38:28 X app/web.1     at _addListener (node:events:587:17) 
Sep 02 16:38:28 X app/web.1     at EventEmitter.addListener (node:events:605:10) 
Sep 02 16:38:28 X app/web.1     at RedisConnection.init (/app/node_modules/bullmq/dist/cjs/classes/redis-connection.js:118:22) 
Sep 02 16:38:28 X app/web.1     at new RedisConnection (/app/node_modules/bullmq/dist/cjs/classes/redis-connection.js:57:34) 
Sep 02 16:38:28 X app/web.1     at new FlowProducer (/app/node_modules/bullmq/dist/cjs/classes/flow-producer.js:24:27)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment] 2023-09-03 08:37
I think you would agree that "Multiple calls to an API endpoint that creates a flow according to the above code." is not enough for any of us to reproduce said issue. Please provide some simple test code without dependencies that reproduces the issue and we will look into it.

**Comment by nordicgit70** [comment] 2023-09-03 17:40
Hereby the test code that re-produces the problem inside a single request. However the issue also occurs without loop and when calling the API several times.

```
import type { NextApiRequest, NextApiResponse } from 'next';
import { Queue, FlowProducer } from 'bullmq';
import { connectBullMQ } from 'utils/ioredis';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
    const io = connectBullMQ();
    const queue = new Queue('#2166', {
        connection: io,
    });

    for (let i = 0; i < 10; i++) {
        new FlowProducer({ ...queue.opts });
    }

    res.status(200).json({ message: 'Hello from Next.js!' });
}
```

And the log files.
```
(node:39852) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39852) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
(node:39852) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
(node:39852) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
```

**Comment by manast** [comment] 2023-09-03 21:22
The reason for the warning is that you are using the same connection for 11 queue instances, as every instance attach some listeners you exceed the maximum number of listeners per object. Remember, this is a warning, there is nothing wrong with it if you know what you are doing. However, the code above is not going to be efficient, as you are instantiating 1 Redis connection, and several Queue instances pre request.
With the code as the one shown above the service is not going to survive a lot of requests... change it so something like this instead:
```ts

 const io = connectBullMQ();
 const queue = new Queue('#2166', {
   connection: io,
 });

 for (let i = 0; i < 10; i++) {
   new FlowProducer({ ...queue.opts });
 }

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
   
   await queue.add(...)
  
   ...
   res.status(200).json({ message: 'Hello from Next.js!' });
}
```

Finally, it is pretty weird to create 11 identical FlowProducer instances, I do not see the point with it...

I hope this clarifies why it happens, I am closing now as there is no issue in BullMQ regarding this warning.

**Comment by manast** [comment] 2023-09-04 11:59
> In my real code there is one FlowProducer and the endpoint is called multiple times. I think the issue is that the FlowProducer is kept in memory with listeners beyond the life-time of the request. Is that working as designed?

The listeners are attached when you instantiate a flow producer, so yes it works as designed. You should close the producer though for gracefully shutting down your service, but you only do this once, not per request.

**Closed by manast** 2023-09-04 11:59 UTC
Labels: bug
