### ISSUE TITLE
Repeating job failing

### ISSUE THREAD

**Issue by PaulGrimshaw** [taskforcesh/bullmq#210] opened 2020-05-26 08:49 UTC
I have a frequent job that runs every 20seconds, but for some reason it just fails at some point, and the job is not added again to the queue.  When i look in the queue there is 0 in "delayed", and all the rest are in "completed".

Any idea what might be causing this behaviour?

I have implemented a hard locking using Redlock to get "at most once" behaviour as its critical my jobs never run at the same time.

This is a sandboxed worker, and runs across multiple servers sharing the redis instance.

```

export default async (bullJob: Job) => {
    const EventEmitter = require("events")
    EventEmitter.defaultMaxListeners = 50
    process.setMaxListeners(50)

    const { job, redlock, fullQueueName, timeoutSec, jobLogger } = await prepareJobRun(bullJob)
    const lock = await tryGetLock(redlock, `bull:${fullQueueName}_lock`, timeoutSec, jobLogger)

    let result = "OK"
    try {
        await Promise.race([job.run(bullJob.data || {}), jobTimeoutError(timeoutSec)])
    } catch (err) {
        result = `ERROR: ${err.message}`
        console.error(err)
        jobLogger.error(err)

        throw err
    } finally {
        jobLogger.info({ message: "Job finished", result })
        await new Promise(resolve => setTimeout(resolve, 10))

        try {
            await lock.unlock()
        } catch (err) {}
    }
}
```

I start the scheduler like this:

```
 const scheduler = new QueueScheduler(fullQueueName, { connection })
 const jobRunner = require(queueFilePath).default
```

**Comment by PaulGrimshaw** [comment] 2020-05-26 19:22
I think this is related to #168

**Comment by manast** [comment] 2020-05-26 21:18
Before digging more into this issue, regarding at most once, you can achieve the same result with bullmq actually. This should be better explained in the docs. The default value for ```maxStalledCount```  in QueueScheduler is 1, meaning that it will retry a stalled job max one, but if you set it to 0 then it will never retry stalled jobs they will just fail if the worker for some reason blocks the process for more than 30 seconds (or is incapable of updating the lock for some reason like a network disconnection, etc)

**Comment by PaulGrimshaw** [comment] 2020-05-27 05:38
Ok that makes sense.  I do have some long running jobs (10min) which are quite heavy on the database and this was the reason for the lock, as I need to avoid the risk that these ever run in parrallel.

So for my understanding:

- Max stalled count is purely for restart of job in current cycle
- Max stalled count = 0 will never restart job, but it will still repeat after defined cron period
- Max concurrency = 1 will never run job more than once, regardless of how many workers are working the queue?

Importantly, sometimes the job repeat interval occurs before the actual job has finished if a run goes slow, and as the last job is still running it the next one should fail.  Would this behaviour be respected by the concurrency setting?

**Comment by manast** [comment] 2020-05-27 07:21
There is one assumption that is not correct, if a repeatable job takes more time to execute than the repeat interval then another worker can start working on the next iteration of the job, so then you may still need to have a separate lock to just ignore the next repetition if it happens while another worker is still working on the previous job.

**Comment by PaulGrimshaw** [comment] 2020-05-27 14:23
Ok. Out of interest, is there a way to have maxConcurrency = 1 work across multiple workers or just within the 1 worker?  I think having consistent "at most once" behaviour across mulitple workers on a queue would be a common requirement, as often the bottle neck is not the worker but load on a target database etc.

**Comment by PaulGrimshaw** [comment] 2020-05-27 14:34
If i was dreaming a wish list, we would like to see the following (not sure if any of this currently possible).

1. Concurrency per queue can be specified (e.g. max 3 jobs running at any time in this queue)
2. Concurrency per job can be specified (eg. this jobId/name can only run one at a time)
3. An option for repeated jobs to not start if previous one still running
4. An option for setting timeout on any sandboxed job (we have implemented this as above)
5. An option to get the full error object / stack trace though QueueEvents for sandboxed jobs

**Comment by manast** [comment] 2020-05-27 21:24
4 and 5 are possible, but 1-3 is quite hard to do.

**Comment by PaulGrimshaw** [comment] 2020-05-28 15:23
Ok appreciated.

Back to the point of the main question, is there any plan to look into this?  We're living a little nervously at the moment as a lot of our jobs are critical - ideally we'd stay with bullmq and not rollback to bull

**Comment by manast** [comment] 2020-05-28 16:16
I started to look into this yesterday, with luck today I will be able to fix it.

**Comment by manast** [comment] 2020-05-28 22:16
Will close as a duplicate of #168

**Closed by manast** 2020-05-28 22:16 UTC
