### ISSUE TITLE
Undefined/empty jobs

### ISSUE THREAD

**Issue by jaschaio** [taskforcesh/bullmq#248] opened 2020-08-02 14:55 UTC
I am having a lot of failed jobs, but when I try to get them via:

```js
const jobs = await queue.getJobs( [ 'failed' ] );
```

They are returned as `undefined`. e.G.:

```js
[ undefined, undefined, undefined, ... ]
```

As I can't get the job ID this way, I double checked which keys it is trying to get by setting `process.env.DEBUG = "ioredis:*";`. When I manually check one of the keys that returns an `undefined` job via the `redis-cli` I get an empty result:

```
HGETALL bull:short:825F243AD7000000CF2B022C0100296E5A100417BA75E26AFC434291F746A7608C065246645F696400645F243AD7DE5C4A0015CB2CDD0004
(empty array)
```

Any reason how this could happen or how I could investigate further?

**Comment by Anushil98** [comment] 2020-09-05 15:13
same here please help !!!!!

**Comment by manast** [comment] 2020-09-06 21:00
Can you provide some code that reproduces the issue?

**Comment by Anushil98** [comment] 2020-09-10 05:35
Our team used Bull to solve the issue we had used a similar code snippet as mentioned in the first comment.
In our use case we tried to use the getJobs and getWaiting  for fetching the last n jobs in the queue inside a cron job for a certain purpose. The getWaitingCount gives us the correct job count but when we use the getJobs we get an array of undefined jobs. The main issue here is that this exact use case works in bull but not in bullmq.

Code couldn't be shown due to confidential information.
Thanks for responding.

**Comment by manast** [comment] 2020-09-10 07:08
you do not need to provide code that is confidential, just a test case that demonstrates the issue. Thing is, we have tests that cover this case and it works, so it must be something else that affects the results:
https://github.com/taskforcesh/bullmq/blob/master/src/test/test_getters.ts

**Comment by Mikkal24** [comment] 2021-03-23 04:41
I ran into a similar issue with the 'repeat' job type. I expected getJobs to return an array of jobs but, instead I got an array of 'undefined' which is weird. 

I wrote a test inside `test_getters.ts` like manast suggested to make sure I'm not crazy.

```  it('should return repeat jobs', async function(done) {
    try {
      await queue.add(
        'test',
        { foo: 1 },
        {
          repeat: {
            every: 15000,
          },
        },
      );

      const jobs = await queue.getJobs('repeat');
      expect(jobs[0]?.data?.foo).to.equal(1);
    } catch (e) {
      return done(e);
    }
  });
  ```

Anyway,  I hope this issue gets resolved soon since I'd like more data than what the `getRepeatableJobs()` call gives me.

**Comment by Mikkal24** [comment] 2021-03-23 04:47
literally minutes after posting I realized that the job type I'm looking for is "delayed" not "repeat" smh. I'll leave my post in case any other google wanderers run into the same problem lol.

**Comment by cchepeau-mwb** [comment] 2022-03-18 20:56
I'm having the same exact issue. :(

redis 6.2
bullmq 1.77.1

**Comment by cchepeau-mwb** [comment] 2022-03-18 21:22
OK nvm. I was wrongly using redis prefixes at the connection options... bull wasn't able to retrieve the jobs data..

**Comment by BohdanKov** [comment] 2022-11-21 14:54
I have a similar problem. I am getting an `undefined` in an array when calling `getJobs()`. It happens every time when I try to create a delayed job.

redis 7.0
bullmq 3.2.2

**Comment by manast** [comment] 2022-11-21 15:26
@BohdanKov can you please create a minimal reproducible case and a new issue with the test code?

**Comment by BohdanKov** [comment] 2022-11-23 10:13
> @BohdanKov can you please create a minimal reproducible case and a new issue with the test code?

@manast created an issue [#1546](https://github.com/taskforcesh/bullmq/issues/1546)

**Comment by roggervalf** [comment] 2022-11-24 02:19
I think it should be related to our new marker strategy for delayed jobs, there is an special id '0:${delay}', this value is added in wait list when the list is empty and delayed jobs are added, so the worker wakes up and it can know how much time has to wait until promote the delayed job. As this value is only used for this purpose, it is not related to any job info, so in getJobs function this value will be null

**Comment by maraujop** [comment] 2023-03-30 11:10
And is there any workaround or fixed for that? Thanks in advance

**Comment by yamiyukiharu** [comment] 2023-08-22 11:54
having this issue as well, +1

**Comment by roggervalf** [comment] 2023-08-22 14:42
Hey, we added this change to skip delayed markers https://github.com/taskforcesh/bullmq/commit/816376e7880ae0eafe85a1f9a5aef9fdfe3031a9 some time ago, in case you are using a greater versión, a reproducible test case could help us to make a fix

**Comment by manast** [comment] 2024-11-13 10:04
Closing. If anybody gets this issue again and has some code to reproduce it please open a new issue.

**Closed by manast** 2024-11-13 10:04 UTC
Labels: cannot reproduce
