### ISSUE TITLE
Issue with upgrade from 1.50.1 to 1.50.2

### ISSUE THREAD

**Issue by masonhugus** [taskforcesh/bullmq#813] opened 2021-10-12 17:10 UTC
Hi, just reporting that the latest version when msgpack was replaced with msgpackr, we now get this error when trying to run our project. We use the `esm` module (https://www.npmjs.com/package/esm) to load our project.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/msgpackr/dist/index.js
require() of ES modules is not supported.
```

**Comment by manast** [comment] 2021-10-14 01:48
@masonhugus Is it even needed to use ESM on node versions 12+ ? Could you consider not using it anymore, seems to be a deprecated project nowadays (2 year since last update).

**Comment by manast** [comment] 2021-10-14 01:52
The irony here is that msgpackr tries to be compatible with both pre node 12 (i.e. no es6 module support) and post 12, still the polyfill (ESM) that tries to solve this problem in a generic way fails when it shouldn't do anything as it is already working!.

**Comment by lukepolo** [comment] 2021-10-14 01:54
Is 1.50 compatible with 1.49 jobs? Just curious

**Comment by manast** [comment] 2021-10-14 01:55
@lukepolo sure. This is just an optimized way to pass args and options to the script, but the data is still stored in the exact same way.

**Comment by manast** [comment] 2021-10-15 02:10
> @manast yeah, that's something we'll look into doing. This isn't the first time a package has done that, though it was a bit surprising to see a breaking change like this on a patch update.

Well, it was not supposed to be a breaking change, in fact before this was merged we got the maintainer of msgpackr to release a change that allowed msgpackr to support node 10 as well. Maybe somebody that knows better can give us a hint on what changes to make in msgpackr so that this issue goes away.

**Comment by roggervalf** [comment] 2021-10-15 02:51
Probably, it's related to https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for, right now I'm afk until Sunday, then I can submit a pr into msgpackr to try to fix this issue, or maybe in the midtime someone could help on creating it sooner 😄

**Comment by kriszyp** [comment] 2021-10-17 17:01
I responded on @roggervalf 's PR (thank you!), but thought I would look for clarification here too: If I understand correctly, the problem is that there is an attempt to `require` msgpackr, and node (an older version?) is ignoring the `exports` directive to use node.cjs, and loading the wrong file (require should load `dist/node.cjs` not `dist/index.js` according to the package.json). Perhaps this could be fixed by changing msgpackr's `main` to point to `dist/node.cjs`? My only concern would be if there are other bundlers that only support `main` and incorrectly bundle the unnecessary node code?

**Closed as completed** 2021-10-18 02:50 UTC
Labels: released
