### ISSUE TITLE
[Bug]: Sandboxed processors, require() of ES Module not supported

### ISSUE THREAD

**Issue by richard-s-popov** [taskforcesh/bullmq#1698] opened 2023-02-18 02:09 UTC
### Version

v3.7.0

### Platform

NodeJS

### What happened?

I'm trying to use Sandboxed processors, I made separate file processor.js:

```
import { Job } from "bullmq";

export default async function (job) {
  await job.log("Start processing job");
  console.log("Doing something useful...", job.id, job.data);
}
```

but always receive an error in bullmq:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/registration/utils/processor.js from /root/registration/node_modules/bullmq/dist/cjs/classes/child-processor.js not supported.
Instead change the require of processor.js in /root/registration/node_modules/bullmq/dist/cjs/classes/child-processor.js to a dynamic import() which is available in all CommonJS modules.
    at ChildProcessor.init (/root/registration/node_modules/bullmq/dist/cjs/classes/child-processor.js:25:25)
    at process.<anonymous> (/root/registration/node_modules/bullmq/dist/cjs/classes/master.js:12:38)
    at process.emit (node:events:513:28)
```

I'm not sure, but I think problem here:
[https://github.com/taskforcesh/bullmq/blob/master/src/classes/child-processor.ts#:~:text=processor%20%3D%20require(processorFile)%3B](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment] 2023-02-19 22:05
We have tests for this and its working, we would need a complete example where this happens so that we can look into it.

**Comment by manast** [comment] 2023-02-19 22:08
Hmm, it could be the import at the top that breaks it:
```
import { Job } from "bullmq";
```

Can you try to use require instead of import?

**Comment by manast** [comment] 2023-02-22 14:34
Did you manage to get it to work?

**Comment by darrinholst** [comment] 2023-04-05 18:45
example of it not working for me - https://github.com/dholst/bullmq-esm-processor

**Comment by eulertour** [comment] 2023-04-23 03:40
I'm doing the same thing as in the example from @darrinholst and getting the same error. Any help/workaround would be appreciated.

**Comment by manast** [comment] 2023-04-23 08:19
> example of it not working for me - https://github.com/dholst/bullmq-esm-processor

Can you try removing ```"type": "module"``` from the package.json?

**Comment by darrinholst** [comment] 2023-04-23 16:47
> > example of it not working for me - https://github.com/dholst/bullmq-esm-processor
> 
> Can you try removing `"type": "module"` from the package.json?

Yes, that works, but most people that come across this are trying to use esm natively. What I did was convert to typescript and transpile down to cjs. That way I can at least use esm syntax.

It’s not ideal as it now introduces a build step where some of us didn’t have one yet (I know ts is eating the world and I caved just to move forward). You also can’t use esm only packages which are becoming much more prevalent.

I ❤️ bull and bullmq, but it’d be even better if we could get esm support.

**Comment by richard-s-popov** [comment] 2023-04-23 16:58
@manast I'm still didn't solve it. In my case I need to use type script, because another library that I use requires "type": "module" in package.json. On the one hand it requires "type": "module", on the other hand (bullMQ) it requires to use "require" and remove "type": "module"

**Comment by HarikalarKutusu** [comment] 2023-04-24 22:35
In my second day of converting my microservice to use bullmq, I hit this, and tried to find the reason for a couple of hours, then I find this issue post :( 

My whole node/express microservices stack is typescript / esbuild / esm modules.

I tried to compile Sandboxed processors separately with esbuild as cjs, and I could! And of course, I hit another error. All my libraries also should also be exposing commonjs versions now :(

Very sad...

**Comment by thangphung1310** [comment] 2023-07-28 11:58
I'm also having the same issue. It's quite inconvenient because I'm also using other libraries that only use esm...

**Comment by manast** [comment] 2023-07-28 12:27
For me what works is this approach: https://blog.taskforce.sh/using-typescript-with-bullmq/
Also, the NodeJS version you use seems to play a big role...
I wish I knew how to solve this issue better but the module resolution in NodeJS is very messy and every time I try to improve it something else breaks, the current state is the best I have been able to do.

**Comment by nandychu** [comment] 2023-07-29 15:49
same problem here...  my whole project it's using esm and therefore I can't use sandboxed workers this way

**Comment by HarikalarKutusu** [comment] 2023-07-29 16:01
> For me what works is this approach

This can work on simple stuff, but when you have complex structures where you depend on other modules it fails. I have my tasks defined in separate modules, which use custom or other modules, so it is no use.

**Comment by amadeogallardo** [comment] 2023-08-13 21:21
Also can reproduce. Attempting to use Sandboxed Jobs fails due to incompatibility with pure ESM modules. I think that Bull MQ should ideally be compatible with pure ESM modules (i.e. `"type": "module"` in `package.json`).

**Comment by rafael-telles** [comment] 2023-10-18 21:12
Any updates on this? I cannot use the workaround of removing `"type": "module"` from package.json, other thirdparty libraries that I use requires it. :(

**Comment by ananni13** [comment] 2023-12-01 09:56
I don't know if there's something wrong in my config or the exports are not correctly defined by bullmq in its package.json, my project is ESM only (`"type": "module"`) but apparently it still loads the CJS version of bullmq at runtime. That might be another thing that needs to be looked at.

Anyway, for sandboxed processors you could modify the `require` into an `await import` inside `child-processor.js` (I needed to change the one inside `dist/cjs/classes` since the esm version is ignored...)

Hacky, patch-package workaround:

```patch
diff --git a/node_modules/bullmq/dist/cjs/classes/child-processor.js b/node_modules/bullmq/dist/cjs/classes/child-processor.js
index 7ce0f47..e5c5909 100644
--- a/node_modules/bullmq/dist/cjs/classes/child-processor.js
+++ b/node_modules/bullmq/dist/cjs/classes/child-processor.js
@@ -24,7 +24,7 @@ class ChildProcessor {
     async init(processorFile) {
         let processor;
         try {
-            processor = require(processorFile);
+            processor = await import(processorFile);
             if (processor.default) {
                 // support es2015 module.
                 processor = processor.default;

```

This seems to fix the issue from my very limited testing.

**Comment by roggervalf** [comment] 2023-12-01 18:48
hi @ananni13 wondering if in you can try this change https://github.com/taskforcesh/bullmq/pull/954/files, pls let us know if that helps

**Comment by manast** [comment] 2023-12-05 10:12
In theory this should work both in commonjs as in ESM: 
```
+            processor = await import(processorFile);
```
So I think it is safe to do this change.

**Comment by manast** [comment] 2023-12-05 10:21
https://github.com/taskforcesh/bullmq/pull/2315

**Comment by chrlyz** [comment] 2023-12-07 02:18
Hi, everyone. Did the last update fix the issue for you? I'm still getting the error with this simple code:


`testJob.ts`
```ts
import { SandboxedJob } from 'bullmq';

export default async (job: SandboxedJob) => {
    const value = Number(job.data.value);
    const result = value + 1;
    return result;
};
```
`test.ts`
```ts
import { Queue, Worker, QueueEvents } from 'bullmq';

const connection = {
    host: '127.0.0.1',
    port: 6379
  }

const postsQueue = new Queue('posts', { connection });
const queueEvents = new QueueEvents('posts', { connection });

const provePostInputs = [1,2,3]

for (const provePostInput of provePostInputs) {
  await postsQueue.add(
    `post${provePostInput}`,
    { provePostInput: provePostInput }
  );

  const worker = new Worker(
    'posts',
    '/home/chrlyz/wrdhom_server/build/testJob.js',
    {connection}
  );
}

queueEvents.on('completed', job => {
    console.log(`${job.jobId} has completed with result ${job.returnvalue}`);
});
```
I wonder if the error is still happening in general or if there's something I need to tweak in my project configuration, since I can see in the error that my test is using the `dist/cjs` files when it may need to be using the `dist/esm` files:

```console
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/chrlyz/wrdhom_server/build/testJob.js from /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js not supported.
Instead change the require of testJob.js in /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js to a dynamic import() which is available in all CommonJS modules.
    at /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:81
    at async ChildProcessor.init (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:25)
    at async process.<anonymous> (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/main-base.js:17:21)
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/chrlyz/wrdhom_server/build/testJob.js from /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js not supported.
Instead change the require of testJob.js in /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js to a dynamic import() which is available in all CommonJS modules.
    at /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:81
    at async ChildProcessor.init (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:25)
    at async process.<anonymous> (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/main-base.js:17:21)
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/chrlyz/wrdhom_server/build/testJob.js from /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js not supported.
Instead change the require of testJob.js in /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js to a dynamic import() which is available in all CommonJS modules.
    at /home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:81
    at async ChildProcessor.init (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/child-processor.js:28:25)
    at async process.<anonymous> (/home/chrlyz/wrdhom_server/node_modules/bullmq/dist/cjs/classes/main-base.js:17:21)

```

**Comment by manast** [comment] 2023-12-07 10:07
Are you sure you are using the latest version? according to the error it seems it is still using require in child-processor.js, but the require has indeed been replaced by a dynamic import.

**Comment by manast** [comment] 2023-12-07 10:08
Here is the code: https://github.com/taskforcesh/bullmq/blob/master/src/classes/child-processor.ts#L29

**Comment by chrlyz** [comment] 2023-12-07 10:46
Yes, I'm sure. I even deleted my `node_modules` directory and `package-lock.json` to make a fresh npm install. I think the issue is related to the fact that in my `node_modules` directory I end up with two directories `node_modules/bullmq/dist/cjs` and `node_modules/bullmq/dist/esm`. The `child-processor.js` file under `esm` actually reflects the change, but it looks like no matter what I do, my process always uses the files under `cjs`, where the `child-processor.js` file there has a `require` where the `import `is being done. Not sure why this happens.

`node_modules/bullmq/dist/cjs`
![cjs](https://github.com/taskforcesh/bullmq/assets/119720482/bd2eb9de-5785-4467-8a9e-f8d6ff6bc4c7)
`node_modules/bullmq/dist/esm`
![esm](https://github.com/taskforcesh/bullmq/assets/119720482/a122eea9-185a-4765-bdcb-8a041310bac8)

**Comment by darrinholst** [comment] 2023-12-07 12:39
@chrlyz what does your typescript config look like? If it's targeting commonjs then it will pick up the cjs directory.

**Comment by manast** [comment] 2023-12-07 13:21
This should do it: https://github.com/taskforcesh/bullmq/pull/2318

**Comment by manast** [comment] 2023-12-07 13:35
Closing as it seems to be resolved now.

**Closed by manast** 2023-12-07 13:35 UTC
Labels: bug, cannot reproduce

**Comment by chrlyz** [comment] 2023-12-07 21:59
It's working for me now too! Thanks!
