### ISSUE TITLE
Redis parser error - ReplyError: ERR timeout is not an integer or out of range

### ISSUE THREAD

**Issue by jcalvento** [taskforcesh/bullmq#985] opened 2022-01-07 13:55 UTC
## Description
I've bumped BullMQ from 1.14.0 to 1.61.0 and started seeing these errors:
```
ReplyError: ERR timeout is not an integer or out of range
command: {
 name: 'brpoplpush',
 args: [ 'bull:Sync:wait', 'bull:Sync:active', '0.402' ]
}

```

Checked the code and I don't see any delay that's not a number plus didn't change any of the delayed jobs I have. Could be that something changed from the other version and there's an old key?
Also checked Redis keys and I can't find any `bull:Sync:wait` or `bull:Sync:active` so I guess it happens while the job runs.
For this particular queue I have a limiter with this config:
```
{
  max: 5,
  duration: 1000,
}
```
## Bull version
1.61.0
## Additional information
Redis version: v5.0

**Comment by ssehacker** [comment] 2022-01-15 12:10
+1

**Comment by manast** [comment] 2022-01-15 14:25
Can you provide a test case that reproduces this?

**Comment by dennypradipta** [comment] 2022-01-17 04:08
+1 I do have the same problem

**Comment by manast** [comment] 2022-01-17 04:17
ah ok, I think this is due to Redis version. Up until version 6 it could only be an integer instead of a double: https://redis.io/commands/brpoplpush#history
So if you can upgrade redis version the error will go away, until we can figure out a fix that works on older versions too.

**Comment by manast** [comment] 2022-01-17 04:55
I released a fix for this but I highly encourage you to upgrade to latest Redis version...

**Closed** 2022-01-17 04:54 UTC

**Comment by dennypradipta** [comment] 2022-01-17 05:16
I used BullMQ 1.59.x and use Redis 6.2.6 when I got that ERR timeout and downgraded it to 1.14 just like the OP did. Which version of Redis did you use?

**Comment by manast** [comment] 2022-01-17 06:05
@dennypradipta if the error is exactly the same as the poster then I find it unlikely that you really were using Redis 6.2.6, maybe there is something misconfigured somewhere?

**Comment by dennypradipta** [comment] 2022-01-17 07:14
Sorry, it seems I have two Redis with different versions installed. After using Redis 6.2.6 and using the newest BullMQ, it is now working correctly (Y)

**Comment by jcalvento** [comment] 2022-01-17 11:21
@manast Than you for your help!
