### ISSUE TITLE
Failed Job not removed from queue inspite of {removeOnFail: true}

### ISSUE THREAD

**Issue by djiktra** [taskforcesh/bullmq#1662] opened 2023-02-08 07:21 UTC
New user of bullMq. Adding job to a queue using below method:
async function addSequenceRecieverJob(data) {
    await sequenceSenderQueue.add('sequenceReciever', data, {jobId: data.jobId, removeOnComplete: true, removeOnFail: true});
}

While few jobs were successfully removed from queue on complete or failure, one job was stuck in the queue even after failure (also this  job wasn't visible on the bullboard at all and was silently sitting in reddis ( I can see below info in reddis for this job) ). New jobs with same job id were not getting added to the queue and I was seeing duplicated event getting emitted but kept scratching my head because I wasn't seeing anything on bullboard untill I decided to check reddis directly. 

Is this some known bug? How can I avoid this in future. I don't know what specifically went wrong with this particular job. Also if it failed I would atleast want it to show up on bullboard so I can take some action instead of just missing all future jobs silently. 

![image](https://user-images.githubusercontent.com/92960064/217460819-3198a57d-390f-47ae-8d9f-604c936e0a65.png)

**Comment by manast** [comment] 2023-02-08 07:54
There is no known bug in this regard. Please provide a test case that reproduces it and we will look into it.

**Comment by manast** [comment] 2023-02-08 08:02
Also please make sure that you have a correct maxmemory policy: https://docs.bullmq.io/guide/going-to-production#max-memory-policy

**Comment by djiktra** [comment] 2023-02-08 08:03
Do you know when can we get "missing key for job" failure. 
I don't see any failed sorted set getting created on reddis (which is why it is probably not showing up on bullboard either) and I just see this hanging failure hash for this job id which is preventing new jobs from getting created with same id
![image](https://user-images.githubusercontent.com/92960064/217469605-bcf9126b-18c9-4a9c-b0f1-7e6abe8af579.png)

**Comment by djiktra** [comment] 2023-02-08 08:03
> Also please make sure that you have a correct `maxmemory` policy: https://docs.bullmq.io/guide/going-to-production#max-memory-policy

Yes have the noeviction policy set and my 1GB reddis cluster is probably on less than 10percent usage

**Comment by manast** [comment] 2023-02-08 08:04
This can happen if a job gets stalled and then the worker that was working on it tries to complete the stalled job. But in this case, the stalled job should be picked up by another worker.

**Comment by djiktra** [comment] 2023-02-08 08:06
Yes the job was stalled because I was locally debugging it and the lockDuration time was elapsed , but looks like it reached some partial failed state

**Comment by djiktra** [comment] 2023-02-08 08:08
I don't see any info on this job id anywhere on reddis except at that one place which I posted initially.

**Comment by djiktra** [comment] 2023-02-08 08:10
> This can happen if a job gets stalled and then the worker that was working on it tries to complete the stalled job. But in this case, the stalled job should be picked up by another worker.

yes, the same worker picked it up again and because I was debugging it got stalled again and because max stall count is default to one , the job got failed but it did not get removed

**Comment by djiktra** [comment] 2023-02-08 08:27
**I was able to reproduce the bug**. Any job which gets stalled for couple times (since 1 is the default max stall count) is getting failed while not getting removed from the queue inspite of having {removeonFail: true}. I added a new job with custom key "reproducebug", and then stalled the job by putting sleep of more than lockDurtation time in the worker and after couple stalls the job failed and left this hash on reddis. I am now not able to add a new job with the same id and this job id does not show up on bullboard failed tab either.
![image](https://user-images.githubusercontent.com/92960064/217475048-55f5ff7a-6b66-45a1-a591-97cbe8fa6fa1.png)

**Comment by manast** [comment] 2023-02-08 08:41
Ok, I will look into it.

**Comment by manast** [comment] 2023-02-08 08:52
Which version of BullMQ are you using?

**Comment by manast** [comment] 2023-02-08 08:55
nvm, I can reproduce the issue.

**Comment by manast** [comment] 2023-02-08 09:09
Ok, actually I was wrong, I cannot reproduce it, and after examining the tests and the code it seems everything looks correct. So which version of BullMQ are you using? if you are in one of the latest ones then I will need to ask for some piece of code that reproduces it. The tests that cover this functionality are here: https://github.com/taskforcesh/bullmq/blob/master/tests/test_stalled_jobs.ts#L169
I see that the first test case is basically what you are describing, and the test lacks checking that no jobs are left in the Redis, but I checked it manually and it is clean. I will complete the test anyway so that it is covered.

**Comment by manast** [comment] 2023-02-08 09:19
Here is the PR with the new addition to the test to cover this scenario: https://github.com/taskforcesh/bullmq/pull/1664

**Comment by djiktra** [comment] 2023-02-08 16:19
I am on version 3.6.1 and reproduce it consistently with above steps. I am unable to get the job by running queue.getJobs('failed') after it has failed but also unable to create a new job with same id

**Comment by manast** [comment] 2023-02-08 16:31
I will need some code that reproduces the issue, or a clear indication of what is different in our unit test from what you are doing.

**Comment by djiktra** [comment] 2023-02-08 17:38
Ok, I did some more debugging. There are multiple issues here.

1. You are missing an await in your unit test on line 36 before delay, so the jobs are never even stalling in your unit tests.
2. I don't know why but even with the lockduration of 1000 and delay of 10000 in worker, job is still not stalling and getting completed like usual (which is strange and you might want to see why). Reducing the lockduration to 100 stalls the job.
3. Last and foremost the issue is happening when job is stalling more than once, so remove that maxStalledCount: 0 and you will see stalled failed jobs are not getting removed from reddis.

**Comment by manast** [comment] 2023-02-08 17:50
> * You are missing an await in your unit test on line 36 before delay, so the jobs are never even stalling in your unit tests.

You are incorrect, no await is needed there are it is returning the promise from the processor. It works, you can test it.



> * I don't know why but even with the lockduration of 1000 and delay of 10000 in worker, job is still not stalling and getting completed like usual (which is strange and you might want to see why). Reducing the lockduration to 100 stalls the job.

Give me a test that demonstrates it.



> 3\. Last and foremost the issue is happening when job is stalling more than once, so remove that maxStalledCount: 0 and you will see stalled failed jobs are not getting removed from reddis.

Please provide a test case that demonstrates it and I will look into it.

**Comment by djiktra** [comment] 2023-02-08 18:05
What do you mean provide you with a test case. Remove that maxStalledCount:0 and change lockDuration:100 in your unit test and you will have a reproducible case.

**Comment by djiktra** [comment] 2023-02-08 18:07
You don't even need lockDuration:100 if you can verify that your jobs are stalling. For me the jobs were not stalling untill I changed lockDuration to 100. The issue is with jobs that are stalling more than once, so remove maxStalledCount from your unit test and let it fall to default value

**Comment by manast** [comment] 2023-02-08 21:39
It works with any setting of ```maxStalledCount```: https://github.com/taskforcesh/bullmq/pull/1664/files#diff-a96a2c2c28385f8d9ac818a5ea16ea5cd7c90cefab090cb5f130e872a48d1bffR254

**Comment by djiktra** [comment] 2023-02-09 19:13
then jobs are not getting stalled in your test. As I said I had to reduce lock duration and put await to be able to stall jobs. Can you put a check to be sure that jobs are getting stalled in that test.

**Comment by manast** [comment] 2023-02-09 22:05
@djiktra what do you mean they are not getting stalled? of course, they are getting stalled, unless you mean something else. The worker starts processing the jobs, and the workers are forcefully closed before the jobs finalize so they are then considered stalled, moved back to wait and the process starts again for as much as you want, when they reach the maxStalledCount they are failed, and as they have the option removeOnFail enabled they are completely removed from the queue.

**Comment by roggervalf** [comment] 2023-05-24 05:01
this issue should be related to https://github.com/taskforcesh/bullmq/pull/1681, I think it should be fixed since version 3.6.6

**Closed** 2023-05-29 22:07 UTC
Labels: cannot reproduce
