### ISSUE TITLE
[Bug]: can't await worker.run()

### ISSUE THREAD

**Issue by yazinsai** [taskforcesh/bullmq#2128] opened 2023-08-09 09:51 UTC
### Version

v4.7.0

### Platform

NodeJS

### What happened?

`await`ing a `.run()` on worker causes it to wait indefinitely. 

See sample output from the `bullmq-repro` repository linked below.

**Code:**

```ts
(async () => {
  console.log("Starting worker");
  await worker.run();
  console.log("Added job");
  new Queue("worker").add("test", { foo: "bar" });
  console.log("Shutting down");
})();
```

**Output:**

```txt

> bullmq-worker-run-issue@1.0.0 start
> npx --yes tsx index.ts

BullMQ: DEPRECATION WARNING! Optional instantiation of Queue, Worker and QueueEvents without providing explicitly a connection or connection options is deprecated. This behaviour will be removed in the next major release
Starting worker
```

It hangs at the `worker.run()` and the promise never resolves.

### How to reproduce.

Code: https://github.com/yazinsai/bullmq-repro

### Relevant log output

```shell
npm run start

> bullmq-worker-run-issue@1.0.0 start
> npx --yes tsx index.ts

BullMQ: DEPRECATION WARNING! Optional instantiation of Queue, Worker and QueueEvents without providing explicitly a connection or connection options is deprecated. This behaviour will be removed in the next major release
Starting worker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment] 2023-08-09 11:12
This works as designed. The run call will resolve when the worker is closed. Normally you can skip calling ```run``` manually as the ```autorun``` option when instantiating a Worker is true by default.
If you still want to call run manually I recommend you to use it like this:
```ts
worker.run().catch(error =>comsole.error('error', error));
```

**Comment by TomZaiger** [comment] 2023-09-19 06:00
@manast it behaves differently than the autorun feature.
1. The worker autorun is synchronous by the constructor, the run method returns a promise that will never resolve.
2. When autorun is enabled and an error occurs, the worker emits it, while when manually running the error has to be caught as you have shown above.

**Comment by manast** [comment] 2023-09-22 13:09
Not sure what the issue is here so closing for now. It works as designed, maybe you have different expectations on how it should work, but most likely you do not need to await worker.run().

**Closed by manast** 2023-09-22 13:09 UTC
Labels: works as designed

**Comment by dextronox** [comment] 2025-12-11 02:35
This should be added to the documentation somewhere, probably as a comment on the .run method. This behavior isn't obvious at all.
