### ISSUE TITLE
BullMQ EventEmitter Memory Leak

### ISSUE THREAD

**Issue by Dragonizedpizza** [taskforcesh/bullmq#1614] opened 2023-01-04 22:13 UTC
#### (An easy to reproduce test case will dramatically decrease the resolution time.)

Upon adding and removing about 6 jobs (with a 3 minute gap between addition and removal), I get 2 warnings - with the same message `(node:18665) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit`.

![image](https://user-images.githubusercontent.com/70718540/210659457-24c1e198-b558-46d1-870c-6bac10ddc79a.png)

## Bull version

bullmq - ^1.86.4

**Comment by roggervalf** [comment] 2023-01-05 04:46
hi @Dragonizedpizza, kind of a pretty old version, could you please try one of the recent versions and let us know if the issue persist? also it would be nice to have a reproducible peace of code

**Comment by Dragonizedpizza** [comment] 2023-01-05 08:47
> hi @Dragonizedpizza, kind of a pretty old version, could you please try one of the recent versions and let us know if the issue persist? also it would be nice to have a reproducible peace of code

```
(node:20239) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20239) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
(node:20239) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
```

upon using bullmq - ^3.5.2.

My code is
```js
const { Queue, QueueEvents, Worker } = require('bullmq');
const { MessageEmbed, MessageButton, MessageActionRow } = require('discord.js');
const pms = require('pretty-ms');

class Bull {
	constructor(client) {
		this.client = client;
	}

	async scheduler() {
		const events = new QueueEvents('Giveaway', {
			connection: this.client.redis
		});

		await events.waitUntilReady();
	}

	async checker() {
		await this.scheduler();

		const queue = new Queue('Giveaway', { connection: this.client.redis });
		queue.obliterate();

		const db = await this.client.db.getAll('giveaway');

		for (const ga of db) {
			const ended = ga.create + ga.duration - Date.now();
			ga.jobId = (Math.random() + 1).toString(36).substring(2);

			await ga.save();

			await queue
				.add(ga.messageId, { ga }, { jobId: ga.jobId, delay: ended })
				.catch(() => {});
		}
	}

	async add(job, ga, status = 'OnGoing') {
		await this.scheduler();
		const queue = new Queue('Giveaway', { connection: this.client.redis });

		if (status === 'Edited') {
			await queue.remove(ga.jobId);
			await queue.add(
				job,
				{ ga },
				{ delay: ga.duration, jobId: ga.jobId }
			);
			return;
		}
		await queue.add(job, { ga }, { delay: ga.duration, jobId: ga.jobId });
	}
	async remove(ga) {
		await this.scheduler();
		const queue = new Queue('Giveaway', { connection: this.client.redis });

		return await queue.remove(ga.jobId);
	}
	worker() {
		const process = async (job) => {
			const ga = job.data.ga;
			this.giveawayRunning(ga);
		};

		// eslint-disable-next-line no-new
		new Worker('Giveaway', process, { connection: this.client.redis });
	}

	async giveawayRunning(ga, reroll = false) {
		if (ga.ended || ga.status === 'Ended') return;

		let err;
		const guild = await this.client.guilds
			.fetch(ga.guildId)
			.catch(() => (err = true));
		if (err) return;

		ga = await this.client.db.get('giveaway', {
			messageId: ga.messageId
		});

		if (guild instanceof Error) {
			return;
		}

		const channel = await guild.channels
			.fetch(ga.channelId)
			.catch((x) => x);

		if (channel instanceof Error) {
			return;
		}

		const msg = await channel.messages
			.fetch(ga.messageId)
			.catch((er) => er);

		if (msg instanceof Error) {
			if (msg.message === 'Unknown Message') {
				this.updateCancelled(ga, false);
			} else {
				this.client.logger.error(
					`Error while fetching message giveaway for ${ga.messageId}`,
					msg
				);
			}
			return;
		}
		if (!ga.users) return this.updateCancelled(ga, reroll);

		let users = ga.users;
		if (users instanceof Error) {
			return this.client.logger.error(
				'Error fetching users for ending giveaway',
				users
			);
		}

		if (users.length < ga.winners) {
			return this.giveawayEdit(msg, channel, ga, [], reroll);
		}

		const winners = [];

		for (let i = 0; i < ga.winners; i++) {
			const winner = Math.floor(Math.random() * users.length);
			winners.push(users[winner]);
			users.splice(winner, 1);
		}

		await this.giveawayEdit(msg, channel, ga, winners, reroll);
		await this.updateEnded(ga, reroll);
		await this.remove(ga);

		return;
	}

	async giveawayEdit(msg, channel, ga, winners = [], reroll = false) {
		if (!winners.length) {
			const embed = new MessageEmbed()
				.setColor('RED')
				.setTitle('Insufficient users')
				.setDescription(
					`Giveaway cancelled because there aren't enough winners for **${ga.prize}** giveaway.`
				);

			if (!msg.editable) return;

			msg.edit({
				content: '🎉🎉 GIVEAWAY CANCELLED 🎉🎉',
				embeds: [embed],
				components:
					ga.uses === 'Button'
						? [
								new MessageActionRow().addComponents(
									new MessageButton()
										.setEmoji(
											'<a:ConeConfetti:832707668049002536>'
										)
										.setStyle('SUCCESS')
										.setCustomId('_')
										.setDisabled(),
									new MessageButton()
										.setCustomId('__')
										.setEmoji('981799754486919208')
										.setStyle('PRIMARY')
										.setDisabled()
								)
						  ]
						: null
			});

			return await this.updateCancelled(ga, false);
		}

		const row = new MessageActionRow();

		if (ga.uses === 'Button')
			row.addComponents(
				new MessageButton()
					.setDisabled()
					.setStyle('SUCCESS')
					.setCustomId('_')
					.setEmoji('<a:ConeConfetti:832707668049002536>'),
				new MessageButton()
					.setCustomId('__')
					.setEmoji('981799754486919208')
					.setStyle('PRIMARY')
					.setDisabled()
			);

		row.addComponents([
			new MessageButton()
				.setCustomId(`reroll-${ga.messageId}`)
				.setLabel('Reroll')
				.setStyle('PRIMARY'),
			new MessageButton()
				.setCustomId(`delete-${ga.messageId}`)
				.setLabel('Delete')
				.setStyle('DANGER')
		]);

		// eslint-disable-next-line id-length
		const embed = new MessageEmbed()
			.setColor(ga.endColor)
			.setTitle('Giveaway Ended')
			.setThumbnail(
				ga.image.thumbnail ?? channel.guild.iconURL({ dynamic: true })
			)
			.setDescription(
				[
					`The giveaway has ended, and the winners are ${convertPluralIds(
						winners.map((x) => `<@${x}>`)
					)}.`
				].join('\n')
			)
			.setImage(
				ga.image.image ??
					'https://images-ext-1.discordapp.net/external/q8kRggqJImI_7n0fdbHRRzlvun_RQxJ856BLhf55kgY/https/i.imgur.com/GUEUhHv.gif?width=418&height=3'
			);

		if (winners.length) {
			channel.send(
				` Congratulations! ${convertPluralIds(
					winners.map((x) => `<@${x}>`)
				)} won \`${ga.prize}\`.`
			);
		}

		msg.edit({
			embeds: [embed],
			components: [row],
			content: this.repl(ga.messages.start, ga, winners)
		});
		await this.updateEnded(ga, reroll);

		return;
	}

	async updateCancelled(ga, reroll) {
		if (reroll) return;

		return await this.client.db.updateOne(
			'giveaway',
			{ messageId: ga.messageId },
			{ $set: { ended: true, status: 'Cancelled' } }
		);
	}

	async updateEnded(ga, reroll) {
		if (reroll) return;

		await this.remove(ga.jobId);

		return await this.client.db.updateOne(
			'giveaway',
			{ messageId: ga.messageId },
			{ $set: { ended: true, status: 'Ended' } }
		);
	}

	repl(text, data, winners) {
		return text
			.replace(/{winners}/g, winners)
			.replace(/{hosted}/g, `<@${data.host}>`)
			.replace(/{prize}/g, data.prize)
			.replace(/{duration}/g, pms(data.duration))
			.replace(/{winnercount}/g, data.winners);
	}

	async wait(time) {
		return await new Promise((resolve) => {
			setTimeout(() => resolve(true), time);
		});
	}
}

module.exports = Bull;
```

**Comment by ajmnz** [comment] 2023-01-06 23:01
👋

I've also encountered the same issue (using version 3.2.4)

```
(node:76021) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at EventEmitter.addListener (node:events:619:10)
    at RedisConnection.init (/<omitted>/node_modules/bullmq/dist/cjs/classes/redis-connection.js:125:22)
    at new RedisConnection (/<omitted>/node_modules/bullmq/dist/cjs/classes/redis-connection.js:54:34)
    at new QueueBase (/<omitted>/node_modules/bullmq/dist/cjs/classes/queue-base.js:38:27)
    at new Worker (/<omitted>/node_modules/bullmq/dist/cjs/classes/worker.js:28:9)
    at new Worker (/<omitted>/packages/framework/dist/queue/Worker.js:7:9)
    at LeadImportQueue.<anonymous> (/<omitted>/packages/framework/dist/queue/Queue.js:45:28)
    at Generator.next (<anonymous>)
```

In our case, (I think) it happens when adding workers to a queue (we have 2 queues, 5 workers each — 10 workers).

This is our Worker class (just a more type-safe wrapper around the native bullmq worker)

```ts
class Worker<
  T extends Queue,
  J extends Awaited<ReturnType<T["addJob"]>>
> extends BullWorker<J["data"], J["returnvalue"]> {
  constructor(
    queue: T,
    handler: Processor<J["data"], J["returnvalue"]>,
    options: WorkerOptions
  ) {
    super(queue.bull.name, handler, options);
  }
}
```

This is the function that adds a worker

```ts
  /**
   * Add a new worker for this queue.
   */
  public async addWorker() {
    const currentWorkers = await this.bull.getWorkers();

    if (currentWorkers.length + 1 > this.workerSize) {
      this.logger.warn(
        `Could not add worker to ${this.bull.name} (maximum amount reached)`
      );

      return;
    }

    // Start worker

    const worker = new Worker(this, (job) => this.handleJob(job as any), {
      connection: this.bull.opts.connection,
    });

    this.logger.debug("Worker started");

    // Register event listeners

    worker.on("error", (error) => {
      this.logger.error(error);
    });

    worker.on("completed", (job) => this.handleCompletion(job as any));
  }
```

And to actually add as many workers as the queue desires, we just do:

```ts
for (let i = 0; i < queue.workerSize; i++) {
  await queue.addWorker();
}
```

Let me know if you need anything else!

**Comment by manast** [comment] 2023-01-09 15:30
First of all, this is not a memory leak, just a warning for a *possible* memory leak. In your case you are reusing a connection for many workers so you trigger the warning, you can apply the suggestion provided by the nodejs runtime ```Use emitter.setMaxListeners() to increase limit``` as printed in your error stack.
Furthermore, I do not see the point in instantiating several Worker instances if you are using the same Queue, just increase the concurrency factor for 1 instance of the worker. Also, in your code you are creating new instances of the class Queue everytime you call "add", and never closing it. That would be a real memory leak, since you do not free the resources. In reality you can just reuse the same Queue instance for all the "add" calls...

**Comment by Dragonizedpizza** [comment] 2023-01-10 10:29
I see, thank you. Is there any way I can access the Commander instance, and setMaxListeners?

**Comment by manast** [comment] 2023-01-10 10:58
https://nodejs.org/api/events.html#emittersetmaxlistenersn

**Comment by pauliusg** [comment] 2023-02-03 14:54
I see this warning with v3.5.11. I use API endpoint to add tasks to the queue. I reuse Redis client between requests.
```
...
const queue = new Queue(queueName, {
  prefix: this.appConfigService.bullMqPrefix,
  connection: this.redisBullMQClient,
  defaultJobOptions: {
	removeOnComplete: true,
	removeOnFail: 1000,
  },
});

try {
	const queueTaskData: QueueTaskData = {
	  id: task.id,
	  name: task.name,
	  ctx: createTaskContextKey(task.id),
	};

	await queue.add(task.name, queueTaskData, {
		jobId: getJobIdByTaskId(task.id),
		lifo: taskCreateDto.lifo || false,
	});
} finally {
	// Close unsubscribes queue (EventEmitter) events to avoid MaxListenersExceededWarning
	// but does not close Redis connection as connection is shared (as is not created by BullMQ).
	await queue.close();	
}
```
As you see, from a comment in the code, I have previously this issue with event emitter but it was resolved by calling `queue.close()`.

However now it does not help. I am not sure in which BullMQ version it started log warnings because I did quite many updates...

**Comment by nordicgit70** [comment] 2023-09-01 12:06
We also have this issues on our platform and I have been looking into different scenario's to find a solution. Unfortunately without result yet, but wanted to share some thoughts that potentially can help.

```
const io = connectBullMQ();
this.#worker = new Worker<Data, Result>(queue.name, callback, {
    ...options,
    connection: io,
});
...
const concurrency = options.concurrency || 1;
this.#worker.setMaxListeners(10 * concurrency);
```

All our queues and workers have their own Redis connection (no sharing). The Redis connection is passed as IORedis connection  object (not as settings to connect). The queues have max. listeners set to 32 (randomly increased during testing). Workers with concurrency have max. listeners set to 10x concurrency. The logs show that Redis connections are established.

>MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 error listeners added to [Commander]. Use emitter.setMaxListeners() to increase limit 

The number 33 indicates that the issue is with the listeners on the queue connections (not worker). There are several log entries for the different queues. We did not start bull-board since the dyno started. So IMO bull-board does not cause the issue. 

> Notes, the worker will create a duplicated connection that it needs internally to make blocking connections.

Could it be that the worker re-uses the queue's connection (to make blocking connections) when it receives an IORedis connection object? And that this increases the number of listeners more than expected? Furthermore what is reasonable as max. listeners?

BullMQ v4.8.0
ioredis v5.3.2
@bull-board/express v5.8.0

**Comment by manast** [comment] 2023-09-01 21:18
@nordicgit70 The concurrency factor of a worker has literally nothing to do with the warning, as the concurrency factor does not result in any more listeners attached to the ioredis client instance. Other than that it is impossible to say what is causing the warning message in your particular case without more details, preferably with a reproducible piece of code. 
As this is not an issue in BullMQ and keeping this issue open may give the impression that it is I am closing it now. If you have a concrete example that produces these warnings please open a discussion and we can give you hints on how to reduce them.

**Closed by manast** 2023-09-01 21:18 UTC

**Comment by nordicgit70** [comment] 2023-09-03 17:43
Register a separate issue #2166 where  MaxListenersExceededWarning is triggered after calling FlowProducer.

**Comment by jonit-dev** [comment] 2024-04-04 17:19
Solved when updating mullmq
